#SKRIPT FILE WITH MISSING SKRIPT PATTERNS
#COPYRIGHT JOHN HEIKENS

#literal boolean
expression (true|false):
    return type: boolean


expression %object% (is|=) %object%:
    return type: boolean

expression console:
    return type: commandsender

expression at:
    return type: direction

expression block at %location%:
    return type: block
    set:
#		(internal code)
    delete:
#		(internal code)

expression %number% times:
    return type: numbers

expression [%number%] (tick|second|minute|hour|day|month|year)[s]:
    return type: timespan

effect wait %timespan%:
    trigger:
#       (internal code)
function floor(n: number) :: number:
    return rounded down {_n}

# spawn 3 creepers at the targeted block
# spawn a ghast 5 meters above the player
effect:
    patterns:
        (spawn|summon) [%number% of] %entitytypes% [%directions% %locations%]
